POST http://localhost:8080/registration/signup
Content-Type: application/json

{
     "firstName": "emeka",
     "lastName": "nkuku",
     "email": "emekankuku@gmail.com",
     "password": "lanique999"
 }

###

POST http://localhost:8080/registration/signin
Content-Type: application/json
# Accept: application/json
# Access-Control-Allow-Credentials: true

{
     "email": "emekankuku@gmail.com",
     "password": "Asdfghjkl1;"
 }

###

POST http://localhost:8080/registration/signin
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
     "email": "ravymiyazaki@gmail.com",
     "password": "Asdfghjkl2;"
 }

###

GET http://localhost:8080/registration/currUser

###

GET http://localhost:8080/registration/all-cookies

###

GET http://localhost:8080/registration/logout