POST http://localhost:8080/registration/signup
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true

{
     "firstName": "ravy",
     "lastName": "miyazaki",
     "email": "ravymiyazaki@gmail.com",
     "password": "Asdfghjkl2;",
     "role": "Manager"
 }

###

POST http://localhost:8080/registration/signin
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
     "email": "ravymiyazaki@gmail.com",
     "password": "Asdfghjkl2;"
 }

###

POST http://localhost:8080/grouping/createGroup
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
     "groupName": "groupa",
     "userEmail": "ravymiyazaki@gmail.com"
 }

###

POST http://localhost:8080/schedule/createSchedule
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true

{
    "email": "ravymiyazaki@gmail.com",
    "group": "groupa",
    "sunday": "02:00-22:00",
    "monday": "02:00-22:00",
    "tuesday": "02:00-22:00",
    "wednesday": "02:00-22:00",
    "thursday": "02:00-22:00",
    "friday": "02:00-22:00",
    "saturday": "02:00-22:00"
}

###

POST http://localhost:8080/schedule/createDaysOff
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true

{
    "email": "ravymiyazaki@gmail.com",
    "group": "groupa",
    "startYear": "2023",
    "startMonth": "06",
    "startDay": "20",
    "endYear": "2023",
    "endMonth": "06",
    "endDay": "20",
    "note": "I am sick"
}

###

POST http://localhost:8080/grouping/getSchedules
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
    "name": "groupa"
}

###

POST http://localhost:8080/grouping/getDaysOff
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
    "name": "groupa"
}

###

POST http://localhost:8080/grouping/addUser
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
     "name": "groupa",
     "managerEmail": "ravymiyazaki@gmail.com",
     "employeeEmail": "emekankuku@gmail.com"
 }

###

POST http://localhost:8080/grouping/getUsers
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
     "name": "groupa"
 }

###

POST http://localhost:8080/grouping/getGroups
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true


{
     "firstName": "Ravy",
     "lastName": "Miyazaki",
     "email": "ravymiyazaki@gmail.com",
     "role": "Manager"
 }

### 

POST http://localhost:8080/registration/deleteUser
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true

{
     "email": "ravymiyazaki@gmail.com"
 }

###

POST http://localhost:8080/grouping/deleteGroup
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true

{
     "name": "groupa"
 }

###

POST http://localhost:8080/schedule/deleteSchedule
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true

{
    "email": "ravymiyazaki@gmail.com",
    "group": "groupa"
}

###

POST http://localhost:8080/schedule/deleteDaysOff
Content-Type: application/json
Accept: application/json
Access-Control-Allow-Credentials: true

{
    "email": "ravymiyazaki@gmail.com",
    "group": "groupa"
}